// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/clinics.ts";
import * as $3 from "./routes/api/clinics/[id].ts";
import * as $4 from "./routes/api/jokes.ts";
import * as $5 from "./routes/api/jokes/[id].ts";
import * as $6 from "./routes/api/jokes/random.ts";
import * as $7 from "./routes/clinics.tsx";
import * as $8 from "./routes/clinics/[id].tsx";
import * as $9 from "./routes/clinics/new.tsx";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Jokes.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/clinics.ts": $2,
    "./routes/api/clinics/[id].ts": $3,
    "./routes/api/jokes.ts": $4,
    "./routes/api/jokes/[id].ts": $5,
    "./routes/api/jokes/random.ts": $6,
    "./routes/clinics.tsx": $7,
    "./routes/clinics/[id].tsx": $8,
    "./routes/clinics/new.tsx": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Jokes.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
